### ISSUE TITLE
demo运行报Bean注入异常

### ISSUE THREAD

**Issue by bigbearLoveTingting** [jackieonway/sms-spring-boot-project#1]
你好，大佬，喜欢你那个短信平台的适配项目，但是我到导下来你的demo跑步起来，报bean注入异常
`org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'helloController': Unsatisfied dependency expressed through field 'aliSmsService'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.github.jackieonway.sms.service.SmsService' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true), @org.springframework.beans.factory.annotation.Qualifier(value=aliSmsService)}`

**Comment by jackieonway** [comment]
您的配置文件的sms-type没有切换成阿里的导致的，您将sms-type切换成ali之后，再运行就不会出现该问题

**Comment by bigbearLoveTingting** [comment]
能否给个联系方式呢，我想在你的代码上做扩展，扩展其他的几个短信平台，但是现在有点问题想请教下，本人qq:846445745 wx:18397779379




------------------ 原始邮件 ------------------
发件人: "jackieonway"<notifications@github.com>; 
发送时间: 2019年7月18日(星期四) 上午9:20
收件人: "jackieonway/sms-spring-boot-project"<sms-spring-boot-project@noreply.github.com>; 
抄送: "这不是演习"<846445745@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [jackieonway/sms-spring-boot-project] demo运行报Bean注入异常 (#1)




您的配置文件的sms-type没有切换成阿里的导致的，您将sms-type切换成ali之后，再运行就不会出现该问题
