### ISSUE TITLE
关于腾讯sms

### ISSUE THREAD

**Issue by hb0730** [jackieonway/sms-spring-boot-project#10]
在查看源码时发现关于腾讯的并非使用的腾讯云最新请求api:https://sms.tencentcloudapi.com/ ,且使用了第三方jar

**Comment by jackieonway** [comment]
此版本是腾讯云短信2.0版本的Java SDK ，详情请见: https://cloud.tencent.com/document/product/382/5976;
后续考虑将腾讯云短信升级为官方提供的最新请求地址。如果您有意协助升级，请参照 https://github.com/jackieonway/sms-spring-boot-project#%E5%A6%82%E4%BD%95%E5%8F%82%E4%B8%8E%E8%B4%A1%E7%8C%AE
