### ISSUE TITLE
高并发不

### ISSUE THREAD

**Issue by xbmchina** [jackieonway/sms-spring-boot-project#14]
如果要发100w条短信的话需要多久时间呀

**Comment by jackieonway** [comment]
没有试过发送大量短信的耗时，耗时的长短跟您选择的短信服务商也有关系，您可以考虑使用异步发送的方式来发送，0.0.3快照版本，提供了异步发送发式，同时提供了本地缓存机制来限制同一数据短时间内重复发送问题，缓存机制暂时不支持针对每条业务数据做设置。
