### ISSUE TITLE
阿里云短信亲测可用，不过要加个配置

### ISSUE THREAD

**Issue by guxsun** [jackieonway/sms-spring-boot-project#3]
spring:
  jackieonway:
    sms:
      sms-type: ali  # 短信服务商 暂目前只有 腾讯和阿里的短信服务，默认为ali 
      sign: ZC # 短信的签名
      access-key: 
      security-key: 
      region-id: cn-hangzhou

**Comment by jackieonway** [comment]
感谢您的验证，是的，需要加region-id才能使用
