### ISSUE TITLE
阿里云批量发送短信有问题

### ISSUE THREAD

**Issue by guxsun** [jackieonway/sms-spring-boot-project#4]
sendBatchTemplateSms方法下的action应该由SendBatchSms改为SendSms，麻烦改了发下包

**Comment by jackieonway** [comment]
这个是参考 https://help.aliyun.com/document_detail/102364.html?spm=a2c4g.11186623.6.615.5e8e56e0M9TXz0#h2-url-4 中的配置，请问是这个配置导致的吗？

**Comment by guxsun** [comment]
https://help.aliyun.com/document_detail/101414.html?spm=a2c4g.11186623.6.616.7078202ap5Kxhh我是看的这个文档，支持对多个手机号发送同一种模板的短信。看了你的源码，你是只取的单个手机号，一个是给多个用户发送同一条短信，一个是给多个用户发送不同的短信。源码可能要改下，稍微有点问题

**Comment by jackieonway** [comment]
已经重新修改后发包，您可以删除已有jar包后重新试下. 谢谢

**Comment by guxsun** [comment]
![image](https://user-images.githubusercontent.com/19874280/61941024-3e4c8400-afc9-11e9-8a96-f9da1cbd1d72.png)

**Comment by guxsun** [comment]
这里的手机号码的格式用你以前的那种，用逗号隔开就行了，另外那种批量发才是转为json格式

**Comment by jackieonway** [comment]
谢谢指正.已经重新修改后发包.
