### ISSUE TITLE
sms-type

### ISSUE THREAD

**Issue by chh-jiang** [jackieonway/sms-spring-boot-project#5]
请问我照着demo做的，为什么application.yml中的sms-type无法通过编译？

**Comment by jackieonway** [comment]
请问，具体的错误信息是什么？

**Comment by LuHanUp** [comment]
好像没有sms-type这个配置啊

**Comment by jackieonway** [comment]
是有的，这个demo是可以运行的，您可以先清除下Maven仓库的jar，重新拉取下，另外请各位把具体的错误日志发上来下，谢谢

**Comment by andyGong-Sterry** [comment]
重新拉去后就没那个问题了，不过页面报错了：{"response":{"request":{"url":"https://yun.tim.qq.com/v5/tlssmssvr/sendsms","method":"POST","body":"{\"sig\":\"47614040e2b177428155d2b882bd1571b136f4c5190c4263d7c8f4c0c602c20f\",\"extend\":\"\",\"ext\":\"\",\"tpl_id\":328921,\"sign\":\"andygong个人公众号\",\"tel\":{\"mobile\":\"17688390725\",\"nationcode\":\"86\"},\"time\":1565698555,\"params\":[\"5678\",\"5\"]}","headers":{"Conetent-Type":"application/json"},"parameters":{"random":"324936","sdkappid":"1210353214"},"connectTimeout":60000,"requestTimeout":60000,"bodyCharset":"UTF-8"},"statusCode":200,"reason":"OK","body":"{\"result\":1014,\"errmsg\":\"package format error, sdkappid not have this tpl_id\",\"ext\":\"\"}","headers":{"Keep-Alive":"timeout=86400","Server":"nginx","Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"POST","Connection":"keep-alive","Content-Length":"87","Date":"Tue, 13 Aug 2019 12:15:56 GMT","Access-Control-Allow-Headers":"X-Requested-With,Content-Type","Content-Type":"application/json;charset=utf-8"}},"result":1014,"errMsg":"package format error, sdkappid not have this tpl_id","ext":"","sid":"","fee":0}
配置都是没错的

**Comment by chh-jiang** [comment]
![image](https://user-images.githubusercontent.com/50479930/62941216-1f8f1f80-be08-11e9-9605-b3b068f4f856.png)

**Comment by jackieonway** [comment]
您参考下这个1014的解决方案呢？https://cloud.tencent.com/document/product/382/9558#.E8.BF.94.E5.9B.9E1014.E9.94.99.E8.AF.AF.E5.A6.82.E4.BD.95.E5.A4.84.E7.90.86.EF.BC.9F
看下是不是您的参数配置有问题
