### ISSUE TITLE
期望能够参与项目并贡献

### ISSUE THREAD

**Issue by flanliulf** [jackieonway/sms-spring-boot-project#8]
最近项目中需要用到短信服务，考察了 GitHub 和 Gitee 上的一些项目，最终还是选用了这个项目，不过目前看起来只是做了基础的封装集成，在验证码短信校验及缓存过期、安全防护、短信健康、异步发送等功能方面，希望能够参与贡献，共同完善本项目
ps：我 Fork 了项目，重新整理了一下 REAMDE 文档，已经提交了 Pull Request。
ps：如何能够联系到你，希望留个联系方式

**Comment by jackieonway** [comment]
是的，目前只是做了集成，并未添加更多的功能在里面，非常高兴您能参与并完善这个项目，期待更多的小伙伴能够参与。

**Comment by flanliulf** [comment]
1.兄弟留个联系方式吧，方便沟通；
2.授一下权，方便我建立分支

**Comment by jackieonway** [comment]
QQ：1254825871，添加时备注一下哈
