### ISSUE TITLE
支持华为云短信么

### ISSUE THREAD

**Issue by iamzxj** [jackieonway/sms-spring-boot-project#9]

**Comment by jackieonway** [comment]
现在不支持华为云短信，如果需要的话，您可以考虑将其集成到这个项目中，方便其他的小伙伴来使用

**Comment by joslynSmall** [comment]
TencentSmsService#sendTemplateSms 方法调用完成后走了个抛异常的方法.
![image](https://user-images.githubusercontent.com/18278604/91423011-84d67700-e88a-11ea-984e-09b0d6a210d9.png)

**Comment by jackieonway** [comment]
嗯，这个是重构代码时，忘记加return了，感谢您的指正，将在0.0.3-SNAPSHOT和0.0.3版本中，解决这个问题
